### ISSUE TITLE
Error with .dbm on some linux machines 

### ISSUE THREAD

**Issue by ChrisgKent** [ChrisgKent/primalscheme3#11]
Passes CI on some linux machine, but causes issues with others.  

```ModuleNotFoundError: No module named '_dbm'```

**Comment by antem** [comment]
I have this issue as well.
Machine: 22.04.1-Ubuntu using a new mamba environment with Python 3.11. 



> primalscheme3 --help
> Traceback (most recent call last):
>   File "/home/user/miniforge3/envs/primalscheme3/bin/primalscheme3", line 3, in <module>
>     from primalscheme3.cli import app
>   File "/home/user/software/primalscheme3/primalscheme3/cli.py", line 12, in <module>
>     from primalscheme3.core.msa import parse_msa
>   File "/home/user/software/primalscheme3/primalscheme3/core/msa.py", line 7, in <module>
>     from primalscheme3.core.classes import FKmer, PrimerPair, RKmer
>   File "/home/user/software/primalscheme3/primalscheme3/core/classes.py", line 5, in <module>
>     from primalscheme3.core.mismatches import MatchDB
>   File "/home/user/software/primalscheme3/primalscheme3/core/mismatches.py", line 1, in <module>
>     import dbm.ndbm
>   File "/home/user/miniforge3/envs/primalscheme3/lib/python3.11/dbm/ndbm.py", line 3, in <module>
>     from _dbm import *
> ModuleNotFoundError: No module named '_dbm'

**Comment by tiantian123** [comment]
I meet this issue too. and I tried to solve this problem from https://stackoverflow.com/questions/63525554/no-module-named-gdbm.

**Comment by tiantian123** [comment]
I meet this issue too. and I tried to solve this problem from https://stackoverflow.com/questions/63525554/no-module-named-gdbm. it worked with the follows command:
`sudo cp /usr/lib/python3.10/lib-dynload/_dbm.cpython-310-x86_64-linux-gnu.so /usr/lib/python3.11/lib-dynload/_dbm.cpython-311-x86_64-linux-gnu.so
sudo cp /usr/lib/python3.10/lib-dynload/_gdbm.cpython-310-x86_64-linux-gnu.so /usr/lib/python3.11/lib-dynload/_gdbm.cpython-311-x86_64-linux-gnu.so`

**Comment by tiantian123** [comment]
I meet this issue too. and I tried to solve this problem from 

> https://stackoverflow.com/questions/63525554/no-module-named-gdbm

It worked with the follows command:
`sudo cp /usr/lib/python3.10/lib-dynload/_dbm.cpython-310-x86_64-linux-gnu.so /usr/lib/python3.11/lib-dynload/_dbm.cpython-311-x86_64-linux-gnu.so` 
`sudo cp /usr/lib/python3.10/lib-dynload/_gdbm.cpython-310-x86_64-linux-gnu.so /usr/lib/python3.11/lib-dynload/_gdbm.cpython-311-x86_64-linux-gnu.so`

**Comment by ChrisgKent** [comment]
Thank you. It's great there is a working solution! 

It's annoying it's a python installation issue. I don't really want to include general instructions for people to mess with their python installations. 

In the short term I'll release a working docker image, so people can still use it, while I work on a refactor to remove this dependancy.

I'll leave the issue open so people can find this!

**Comment by tiantian123** [comment]
亲，邮件已收到，非常感谢！

**Comment by tiantian123** [comment]
亲，邮件已收到，非常感谢！

**Comment by ChrisgKent** [comment]
Fixed in 3.1.

Changed behaviour to use dmb.dumb (zero dependency but slow) if dmb.ndbm not installed. Should fix the errors. Will still look into a rewrite if performance becomes a issue.
